package es.iesvirgendelacaridad.etcp.audio
import android.content.Context
import android.media.*
import android.net.Uri
import java.io.File
import java.nio.ByteBuffer
object AudioSegmenter {
 fun segment(context:Context,uri:Uri,maxMinutes:Int=12):List<File>{val extractor=MediaExtractor();extractor.setDataSource(context,uri,null);var audioTrack=-1;for(i in 0 until extractor.trackCount){val f=extractor.getTrackFormat(i);if(f.getString(MediaFormat.KEY_MIME)?.startsWith("audio/")==true){audioTrack=i;break}};require(audioTrack>=0){"No se encontró pista de audio"};extractor.selectTrack(audioTrack);val format=extractor.getTrackFormat(audioTrack);val durationUs=format.getLong(MediaFormat.KEY_DURATION);extractor.release();val segmentUs=maxMinutes*60L*1_000_000L;val out=mutableListOf<File>();var startUs=0L;var index=0;while(startUs<durationUs){val endUs=minOf(durationUs,startUs+segmentUs);val file=File(context.cacheDir,"etcp_${System.currentTimeMillis()}_${index++}.m4a");copyRange(context,uri,file,startUs,endUs);out+=file;startUs=endUs};return out}
 private fun copyRange(context:Context,uri:Uri,outFile:File,startUs:Long,endUs:Long){val ex=MediaExtractor();ex.setDataSource(context,uri,null);var track=-1;for(i in 0 until ex.trackCount){val f=ex.getTrackFormat(i);if(f.getString(MediaFormat.KEY_MIME)?.startsWith("audio/")==true){track=i;break}};require(track>=0);ex.selectTrack(track);ex.seekTo(startUs,MediaExtractor.SEEK_TO_PREVIOUS_SYNC);val mux=MediaMuxer(outFile.absolutePath,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);val muxTrack=mux.addTrack(ex.getTrackFormat(track));mux.start();val buf=ByteBuffer.allocate(2*1024*1024);val info=MediaCodec.BufferInfo();var firstPts=-1L;while(true){val pts=ex.sampleTime;if(pts<0||pts>=endUs)break;buf.clear();val size=ex.readSampleData(buf,0);if(size<0)break;if(firstPts<0)firstPts=pts;info.offset=0;info.size=size;info.presentationTimeUs=pts-firstPts;info.flags=ex.sampleFlags;mux.writeSampleData(muxTrack,buf,info);ex.advance()};mux.stop();mux.release();ex.release()}
}
