package es.iesvirgendelacaridad.etcp.network
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.io.File
import java.util.concurrent.TimeUnit
class OpenAiClient(private val apiKey:String){private val http=OkHttpClient.Builder().connectTimeout(60,TimeUnit.SECONDS).readTimeout(10,TimeUnit.MINUTES).writeTimeout(10,TimeUnit.MINUTES).build();suspend fun transcribeFile(file:File):String=withContext(Dispatchers.IO){val body=MultipartBody.Builder().setType(MultipartBody.FORM).addFormDataPart("model","gpt-4o-transcribe").addFormDataPart("language","es").addFormDataPart("file",file.name,file.asRequestBody("audio/mp4".toMediaType())).build();val req=Request.Builder().url("https://api.openai.com/v1/audio/transcriptions").header("Authorization","Bearer $apiKey").post(body).build();http.newCall(req).execute().use{r->val text=r.body?.string().orEmpty();check(r.isSuccessful){"Error de transcripción ${r.code}: $text"};JSONObject(text).optString("text")}};suspend fun summarizeEtcp(transcript:String):String=withContext(Dispatchers.IO){val prompt="""Analiza íntegramente esta transcripción de una reunión ETCP. No inventes información. Distingue INFORMACION, DEBATE, PROPUESTA y ACUERDO. Extrae responsables, fechas/plazos y pendientes solo cuando consten. Devuelve SOLO JSON válido con: {"sintesis_ejecutiva":"...","temas":[{"titulo":"...","resumen":"...","tipo":"INFORMACION|DEBATE|PROPUESTA|ACUERDO"}],"propuestas":[{"texto":"...","proponente":"..."}],"acuerdos":[{"texto":"...","responsable":"...","plazo":"..."}],"pendientes":[],"observaciones":[]} No conviertas propuestas en acuerdos. TRANSCRIPCION: $transcript""";val payload=JSONObject().put("model","gpt-5.6-luna").put("input",prompt);val req=Request.Builder().url("https://api.openai.com/v1/responses").header("Authorization","Bearer $apiKey").header("Content-Type","application/json").post(payload.toString().toRequestBody("application/json".toMediaType())).build();http.newCall(req).execute().use{r->val raw=r.body?.string().orEmpty();check(r.isSuccessful){"Error de análisis ${r.code}: $raw"};extractOutputText(JSONObject(raw))}};private fun extractOutputText(obj:JSONObject):String{val output=obj.optJSONArray("output")?:return obj.optString("output_text");for(i in 0 until output.length()){val content=output.optJSONObject(i)?.optJSONArray("content")?:continue;for(j in 0 until content.length()){val t=content.optJSONObject(j)?.optString("text").orEmpty();if(t.isNotBlank())return t}};return obj.optString("output_text")}}
